server:
  port: 8000

spring:
  freemarker:
    check-template-location: false
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
  data:
    redis:
      repositories:
        enabled: false

  #配置 Jpa
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true

  redis:
    #数据库索引
    database: ${REDIS_DB:0}
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PWD:}
    #连接超时时间
    timeout: 5000

task:
  pool:
    # 核心线程池大小
    core-pool-size: 10
    # 最大线程数
    max-pool-size: 30
    # 活跃时间
    keep-alive-seconds: 60
    # 队列容量
    queue-capacity: 50

#七牛云
qiniu:
  # 文件大小 /M
  max-size: 15

#邮箱验证码有效时间/秒
code:
  expiration: 300

#密码加密传输，前端公钥加密，后端私钥解密
rsa:
  private_key: MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBANCU9ZcsHU5ZAzK9x3jt6K8SFSFCoGaKAcknloc2/TcqyW/KsmYovkszKNMBfC5kuy6/duyNq4zHXwXMw9oSJttHqvFj6aUmwY6hOuvp7RV2Nme39JC4Awq9MiWlTf0aNet/brijLH2siL8xxh3XQhl/Ceb8lj6V1gs+bteKhg9XAgMBAAECgYButXG5IGgZqrNA3mweqqAjNETU14lNg5i5DPMfp7c07dfnJz4TbTK7tVbI0HP6J+sWP/e+TN+uJDAyYuHdQF8wdI4XJ2wuXbiM12HkrjAKFM6lN9PiI1a5i19U3L0v0sL/UD4oT7Ji/Cmj3urb7445urHWx6+knQL2+jMup2B+wQJBAPXmLgaltf1mcrmWG5dPY6msEKo0rYLXBSclnKsZaxwdEZTeSfzoiffy8O/uNdxJME6zlVYKWv3bomnwgPruzHcCQQDZJlwKZR6nMGt4Bjk7UWHHxB6HgRi5bE7P+Bay2OsaCPgJctImocfPMUg41HpMfCDqXcVHcaZ1/N4d+hTswOwhAkEA2ePU9N7xnFCjZ/+zAyi9zyNAwRFcjoupbT7OzG4Bky/O3HL8bLZBSwxiorgZ0dColZRbx5n1duyfxe/u2muvkQJAHPWEqM47fEh0zJjn4QVFaQK6n4+T4IaVLB8Fx+wtzlcL3Ra29/fzUapc21dayAB100uWF6UMcge7B3xmdfx0gQJBAOGwsaFjT206lIpM3/Q1HCzW6MW9oY9BpHcRsVemy2jVwrHDWL4MKFi506oCWWUkTExzRVPu9n/Ql8IAHbZFdVc=
